=== UO295662/F1Desktop/xml/rutas.dtd
<!ELEMENT rutas (ruta+)>
<!ELEMENT ruta (nombre, tipo, medio_transporte, fecha_inicio?, hora_inicio?, duracion, agencia, descripcion, personas, inicio, referencias, recomendacion, hitos, planimetria, altimetria)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT tipo (#PCDATA)>
<!ELEMENT medio_transporte (#PCDATA)>
<!ELEMENT fecha_inicio (#PCDATA)>
<!ELEMENT hora_inicio (#PCDATA)>
<!ELEMENT duracion (#PCDATA)>
<!ELEMENT agencia (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT personas (#PCDATA)>
<!ELEMENT inicio (lugar, direccion, coordenadas)>
<!ELEMENT lugar (#PCDATA)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT coordenadas (latitud, longitud, altitud)>
<!ELEMENT latitud (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>
<!ELEMENT altitud (#PCDATA)>
<!ELEMENT referencias (referencia+)>
<!ELEMENT referencia (#PCDATA)>
<!ELEMENT recomendacion (#PCDATA)>
<!ELEMENT hitos (hito+)>
<!ELEMENT hito (nombre, descripcion, coordenadas, distancia, galeria_fotos, galeria_videos?)>
<!ELEMENT distancia (#PCDATA)>
<!ATTLIST distancia unidad CDATA #REQUIRED>
<!ELEMENT galeria_fotos (foto+)>
<!ELEMENT foto (#PCDATA)>
<!ATTLIST foto archivo CDATA #REQUIRED>

<!ELEMENT galeria_videos (video*)>
<!ELEMENT video (#PCDATA)>
<!ATTLIST video archivo CDATA #REQUIRED>
<!ELEMENT planimetria EMPTY>
<!ATTLIST planimetria archivo CDATA #REQUIRED>
<!ELEMENT altimetria EMPTY>
<!ATTLIST altimetria archivo CDATA #REQUIRED>

=== UO295662/F1Desktop/xml/rutas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE rutas SYSTEM "rutas.dtd">
<rutas>
    <ruta>
        <nombre>Ruta de los Monumentos Prerrománicos</nombre>
        <tipo>Arquitectura y monumentos</tipo>
        <medio_transporte>A pie</medio_transporte>
        <fecha_inicio>2025-06-15</fecha_inicio>
        <hora_inicio>10:00</hora_inicio>
        <duracion>4 horas</duracion>
        <agencia>NaturaTur</agencia>
        <descripcion>
            Una ruta cultural que recorre los principales monumentos prerrománicos del concejo de Oviedo.
        </descripcion>
        <personas>Apta para toda la familia</personas>
        <inicio>
            <lugar>Plaza del Ayuntamiento</lugar>
            <direccion>Plaza de Alfonso II El Casto, s/n</direccion>
            <coordenadas>
                <latitud>43.3603</latitud>
                <longitud>-5.8442</longitud>
                <altitud>233</altitud>
            </coordenadas>
        </inicio>
        <referencias>
            <referencia>https://es.wikipedia.org/wiki/Foncalada</referencia>
            <referencia>https://www.visitoviedo.info/que-visitar/imprescindibles/prerromanico</referencia>
        </referencias>
        <recomendacion>9</recomendacion>
        <hitos>
            <hito>
                <nombre>La Foncalada</nombre>
                <descripcion>Fuente prerrománica declarada Patrimonio de la Humanidad.</descripcion>
                <coordenadas>
                    <latitud>43.3656</latitud>
                    <longitud>-5.8461</longitud>
                    <altitud>205</altitud>
                </coordenadas>
                <distancia unidad="m">600</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/la_foncalada.jpg">Imagen de La Foncalada</foto>
                </galeria_fotos>
            </hito>
            <hito>
                <nombre>San Julián de los Prados</nombre>
                <descripcion>Iglesia prerrománica construida en el siglo IX.</descripcion>
                <coordenadas>
                    <latitud>43.3675</latitud>
                    <longitud>-5.8372</longitud>
                    <altitud>196</altitud>
                </coordenadas>
                <distancia unidad="m">1300</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/san_julian_delosprados.jpg">Imagen de San Julián de los prados</foto>
                </galeria_fotos>
            </hito>
            <hito>
                <nombre>Santa María del Naranco</nombre>
                <descripcion>Palacio prerrománico convertido en iglesia.</descripcion>
                <coordenadas>
                    <latitud>43.3695</latitud>
                    <longitud>-5.8611</longitud>
                    <altitud>334</altitud>
                </coordenadas>
                <distancia unidad="m">2400</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/naranco.jpg">Imagen de Santa María del Naranco</foto>
                </galeria_fotos>
            </hito>
            <hito>
                <nombre>San Miguel de Lillo</nombre>
                <descripcion>Iglesia prerrománica del siglo IX, ejemplo único del arte asturiano.</descripcion>
                <coordenadas>
                    <latitud>43.3789</latitud>
                    <longitud>-5.8658</longitud>
                    <altitud>366</altitud>
                </coordenadas>
                <distancia unidad="m">800</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/san_miguel_lillo.jpg">Imagen de San Miguel de Lillo</foto>
                </galeria_fotos>
            </hito>
            <hito>
                <nombre>Catedral de Oviedo</nombre>
                <descripcion>Catedral gótica que alberga la Cámara Santa con importantes reliquias.</descripcion>
                <coordenadas>
                    <latitud>43.3622</latitud>
                    <longitud>-5.8439</longitud>
                    <altitud>231</altitud>
                </coordenadas>
                <distancia unidad="m">2500</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/catedral_oviedo.jpg">Imagen de la Catedral de Oviedo</foto>
                </galeria_fotos>
            </hito>
        </hitos>
        <planimetria archivo="rutas.kml" />
        <altimetria archivo="ruta1.svg" />
    </ruta>

    <ruta>
        <nombre>Ruta Gastronómica de Oviedo</nombre>
        <tipo>Gastronómica</tipo>
        <medio_transporte>A pie</medio_transporte>
        <duracion>3 horas</duracion>
        <agencia>Sin agencia</agencia>
        <descripcion>
            Descubre los sabores de Oviedo visitando sidrerías y restaurantes típicos.
        </descripcion>
        <personas>Personas en buena forma física</personas>
        <inicio>
            <lugar>Calle Gascona</lugar>
            <direccion>Calle Gascona, 1</direccion>
            <coordenadas>
                <latitud>43.3639</latitud>
                <longitud>-5.8442</longitud>
                <altitud>233</altitud>
            </coordenadas>
        </inicio>
        <referencias>
            <referencia>https://www.turismoasturias.es/descubre/gastronomia</referencia>
            <referencia>https://gasconaoviedo.es/</referencia>
        </referencias>
        <recomendacion>8</recomendacion>
        <hitos>
            <hito>
                <nombre>Sidrería Tierra Astur</nombre>
                <descripcion>Degustación de sidra y tapas asturianas.</descripcion>
                <coordenadas>
                    <latitud>43.3639</latitud>
                    <longitud>-5.8439</longitud>
                    <altitud>238</altitud>
                </coordenadas>
                <distancia unidad="m">50</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/tierra_astur.jpg">Imagen del Tierra Astur</foto>
                </galeria_fotos>
            </hito>
            <hito>
                <nombre>Restaurante El Fartuquín</nombre>
                <descripcion>Especialidad en cachopos y fabada asturiana.</descripcion>
                <coordenadas>
                    <latitud>43.3594</latitud>
                    <longitud>-5.8433</longitud>
                    <altitud>239</altitud>
                </coordenadas>
                <distancia unidad="m">500</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/fartuquin.jpg">Imagen del Restaurante Fartuquín</foto>
                </galeria_fotos>
            </hito>
            <hito>
                <nombre>Mercado El Fontán</nombre>
                <descripcion>Mercado tradicional con productos locales y puestos de comida típica.</descripcion>
                <coordenadas>
                    <latitud>43.3600</latitud>
                    <longitud>-5.8456</longitud>
                    <altitud>245</altitud>
                </coordenadas>
                <distancia unidad="m">200</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/mercado_fontan.jpg">Imagen del Mercado El Fontán</foto>
                </galeria_fotos>
            </hito>
            <hito>
                <nombre>Casa Ramón</nombre>
                <descripcion>Taberna centenaria especializada en mariscos y pescados frescos.</descripcion>
                <coordenadas>
                    <latitud>43.3594</latitud>
                    <longitud>-5.8453</longitud>
                    <altitud>242</altitud>
                </coordenadas>
                <distancia unidad="m">100</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/casa_ramon.jpg">Imagen de Casa Ramón</foto>
                </galeria_fotos>
            </hito>
            <hito>
                <nombre>Chigre Casa Conrado</nombre>
                <descripcion>Auténtico chigre asturiano con ambiente tradicional y sidra de calidad.</descripcion>
                <coordenadas>
                    <latitud>43.3628</latitud>
                    <longitud>-5.8477</longitud>
                    <altitud>228</altitud>
                </coordenadas>
                <distancia unidad="m">400</distancia>
                <galeria_fotos>
                    <foto archivo="multimedia/casa_conrado.jpg">Imagen del Chigre Casa Conrado</foto>
                </galeria_fotos>
            </hito>
        </hitos>
        <planimetria archivo="rutas.kml" />
        <altimetria archivo="ruta2.svg" />
    </ruta>

    <ruta>
        <nombre>Ruta Paisajística del Monte Naranco</nombre>
        <tipo>Paisajística</tipo>
        <medio_transporte>Bicicleta</medio_transporte>
        <duracion>3 horas</duracion>
        <agencia>Asturias con Bici</agencia>
        <descripcion>
            Una ruta en bicicleta que abraza el Monte Naranco siguiendo senderos y caminos rurales dentro del concejo de Oviedo, combinando patrimonio prerrománico con paisajes naturales.
        </descripcion>
        <personas>Personas en buena forma física</personas>
        <inicio>
            <lugar>Plaza de América (Oviedo)</lugar>
            <direccion>Plaza de América, s/n</direccion>
            <coordenadas>
                <latitud>43.3608</latitud>
                <longitud>-5.8567</longitud>
                <altitud>242</altitud>
            </coordenadas>
        </inicio>
        <referencias>
            <referencia>https://rutas.asturiesconbici.org/ruta/abrazando-al-naranco-i-el-nora-como-vera/</referencia>
            <referencia>https://www.turismoasturias.es/descubre/que-hacer/deportes/cicloturismo</referencia>
        </referencias>
        <recomendacion>9</recomendacion>
        <hitos>
            <hito>
                <nombre>Santa María del Naranco</nombre>
                <descripcion>Palacio prerrománico del siglo IX convertido en iglesia, Patrimonio de la Humanidad UNESCO.</descripcion>
